export enum ApiErrorCode {
  CLIENT_ERROR = 'CLIENT_ERROR',
  BODY_VALIDATION_FAIL = 'BODY_VALIDATION_FAIL',
  NOT_FOUND_ID = 'NOT_FOUND_ID',
  CONFLICT_PCCC = 'CONFLICT_PCCC',
  SERVER_ERROR = 'SERVER_ERROR',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
}
